export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const UPDATE_TAGS_FILTER = 'UPDATE_TAGS_FILTER';
export const UPDATE_MODELS_FILTER = 'UPDATE_MODELS_FILTER';
export const UPDATE_SORT_FILTER = 'UPDATE_SORT_FILTER';
export const UPDATE_STUDIO_FILTER = 'UPDATE_STUDIO_FILTER';
export const UPDATE_DURATION_FILTER = 'UPDATE_DURATION_FILTER';
export const RESET_FILTER = 'RESET_FILTER';